### ISSUE TITLE
Неровная разметка кнопок редактирования

### ISSUE THREAD

**Issue by Matharis** [AureliusVarro/Organizer-front#13]

**Comment by Matharis** [comment]
![image](https://user-images.githubusercontent.com/28714575/57793155-f3003480-7740-11e9-82ff-84520766e0e5.png)

**Comment by AureliusVarro** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/31248614/57982719-e8e87980-7a51-11e9-9b64-12b9a3d1fc0e.png)
