### ISSUE TITLE
Ошибка при создании Note, если отсуствуют Notebook

### ISSUE THREAD

**Issue by Exbifour** [AureliusVarro/Organizer-front#17]
![зображення](https://user-images.githubusercontent.com/28699306/57983011-81ccc400-7a55-11e9-975f-ca02b39f6b87.png)

**Для повторения:**
1. Удалить все Notebooks;
2. Перезагрузить страницу.

_или_

1. Создать нового пользователя
2. Перейти к фиче "Notes".

Если попробовать добавить Note, то приложение выдаст ошибку
![зображення](https://user-images.githubusercontent.com/28699306/57983046-028bc000-7a56-11e9-9111-92e7ced34f6b.png)

**Рекомендация:**
При отсуствии Notebooks у пользователя, в рабочую область вместо текущего интерфейса поместить кнопку "Create notebook".
Заблокировать _ADD NOTE_ button до создания Notebook или создавать Notebook с дефортным названием автоматически при поытки добавления Note, если у пользователя нет Notebooks

**Comment by AureliusVarro** [comment]
fixed
