### ISSUE TITLE
У Cancel button в Edit Note отстутсвует действие

### ISSUE THREAD

**Issue by Exbifour** [AureliusVarro/Organizer-front#18]
![зображення](https://user-images.githubusercontent.com/28699306/57983161-59de6000-7a57-11e9-9527-ca25c5e4a159.png)
Фактически безполезная кнопка. 

**Рекомендация:**
Убрать _Cancel_ button в областе _Edit Note_

**Comment by AureliusVarro** [comment]
fixed
