### ISSUE TITLE
Notes отображаются после удаления Notebook

### ISSUE THREAD

**Issue by Exbifour** [AureliusVarro/Organizer-front#19]
1. Если удалить Notebooks, то связанные с ним Notes продолжают отображаться.

2. Если попробовать удалить одну из таких Notes, то выскакивает ошибка '404 - Note Found'.
![зображення](https://user-images.githubusercontent.com/28699306/57983457-c3ac3900-7a5a-11e9-8e4b-9805f2283e54.png)

3. Если попробовать добавить новый Note или изменить любой из тех, что отображается, то выскакивает ошиюка '400 - Bad Request'
![зображення](https://user-images.githubusercontent.com/28699306/57983481-0a019800-7a5b-11e9-80f7-a3a5d623197c.png)

4. Если попробовать добавить новый Notebook с таким-же названием как и у удалённого - '500 - Internal server error'
![зображення](https://user-images.githubusercontent.com/28699306/57983524-6b296b80-7a5b-11e9-9237-78c29e11c68a.png)

**Рекомендация:**
При удалении проверять, если ли у пользователя другие Notebooks
1. Если есть 1 или более Notebooks - переключить отображение на какой-либо другой Notebook (желательно на тот, что стоял в списке Notebooks выше на одну позицию перед тем, что был удалён).
2. Если Notebooks нет - убрать все элементы интерфейса из рабочей области и отобразить предложение добавить новый Notebook.

**Comment by AureliusVarro** [comment]
fixed
