### ISSUE TITLE
Подправить расположение кнопок

### ISSUE THREAD

**Issue by Exbifour** [AureliusVarro/Organizer-front#26]
Расстояние от правой границы до _Save_ button и между _Save_ button и _Cancel_ button должно быть равно расстоянию от левой границы до _Delete_ button
![image](https://user-images.githubusercontent.com/28699306/58099358-21b85800-7be4-11e9-9016-3fa79c05efbf.png)

**Comment by Exbifour** [comment]
Заодно можно подправить размер кнопок. Хотелось бы чтобы они одинаковой ширины были -- как у _Delete_ button

**Comment by AureliusVarro** [comment]
fixed
