### ISSUE TITLE
Название при отметке To-Do как Done

### ISSUE THREAD

**Issue by Exbifour** [AureliusVarro/Organizer-front#30]
В верхней части списка названия To-Do отображаются правильно.

При отметке Is Done - в нижней части списка название заменяется на описание ToDo.

![зображення](https://user-images.githubusercontent.com/28699306/58122036-6a3a3a80-7c11-11e9-9ca3-a881a1a19878.png)

**Comment by AureliusVarro** [comment]
fixed
