### ISSUE TITLE
При переименовании To-Do List или Notebook название в первой колонке не изменяется

### ISSUE THREAD

**Issue by Exbifour** [AureliusVarro/Organizer-front#31]
При переименовании To-Do List название в первой колонке **не изменяется.**

В списке переключения To-Do Lists и в поле _Select To-Do Lists_ название **изменяются корректно.**

![зображення](https://user-images.githubusercontent.com/28699306/58122155-a53c6e00-7c11-11e9-97a7-e3a284c0e5a2.png)

**Comment by Exbifour** [comment]
Идентичная проблема замечена в Notes

![зображення](https://user-images.githubusercontent.com/28699306/58123090-ba1a0100-7c13-11e9-819f-1360dc8c8500.png)

**Comment by AureliusVarro** [comment]
fixed

**Comment by AureliusVarro** [comment]
fixed
