### ISSUE TITLE
Проблема добавления контакта после редактирования

### ISSUE THREAD

**Issue by Exbifour** [AureliusVarro/Organizer-front#33]
Если отредактировать какой-либо контакт, а потом попробовать добавить новый (не важно с такими же или другими данными), приложение отдаёт "500 - Initial server error".

Лечится перезагрузкой страницы.

**Важно!** Редактирование контактов продолжает работать нормально без перезагрузки.

До перезагрузки:
![зображення](https://user-images.githubusercontent.com/28699306/58122800-13cdfb80-7c13-11e9-908c-6b079255a75a.png)

После перезагрузки:
![зображення](https://user-images.githubusercontent.com/28699306/58122869-39f39b80-7c13-11e9-973f-42a6c8a4d177.png)

**Comment by AureliusVarro** [comment]
fixed
