### ISSUE TITLE
Время при создании ивентов

### ISSUE THREAD

**Issue by Matharis** [AureliusVarro/Organizer-front#7]
Невозможно выбрать время при создании ивентов: на пикер можно кликнуть и поменять, но, в результате, оно останется прежним.

**Comment by Matharis** [comment]
1) Создаем ивент
![image](https://user-images.githubusercontent.com/28714575/57792923-6c4b5780-7740-11e9-9ffa-fc42cbb96a27.png)
2) Меняем время

**Comment by AureliusVarro** [comment]
fixed
