### ISSUE TITLE
Отображение ивента

### ISSUE THREAD

**Issue by Matharis** [AureliusVarro/Organizer-front#8]
Ивент создается неявно. На календаре его увидеть невозможно, хоть и случайно можно открыть его в редакторе.

**Comment by Matharis** [comment]
шаг 1
![image](https://user-images.githubusercontent.com/28714575/57776068-e2d75d80-771e-11e9-9e7c-35dcdc3f2e70.png)

**Comment by Matharis** [comment]
шаг 2: кликаем на любое место
![image](https://user-images.githubusercontent.com/28714575/57776128-f8e51e00-771e-11e9-9553-f5f1565e4739.png)

**Comment by Matharis** [comment]
шаг 3: при нажатии ADD EVENT можно повторять шаги 1 и 2
при нажатии СANCEL и последующим нажатии мы увидим следующее:

![image](https://user-images.githubusercontent.com/28714575/57776236-39dd3280-771f-11e9-8047-210673676a70.png)

**Comment by AureliusVarro** [comment]
fixed
